export default {
  APP_NAME: 'Rablabla',
  REFRESH: 'Refresh',
  GITHUB: 'GitHub',
  PREFERENCES: 'Preferences',
  TIMETABLE_CONNECTION: 'Timetable Connection',
  TIMETABLE_CONNECTION_DESCRIPTION1: 'To access your timetable events we need the rapla link from your university. You should have received it at the start of the semester. At the DHBW it looks like for example',
  TIMETABLE_CONNECTION_SAMPLE1: 'https://rapla.dhbw-stuttgart.de/rapla?key=12345abcdef',
  TIMETABLE_CONNECTION_DESCRIPTION_OR: 'or',
  TIMETABLE_CONNECTION_SAMPLE2: 'https://rapla.dhbw-karlsruhe.de/rapla?page=calendar&user=x&file=inf4',
  TIMETABLE_CONNECTION_LABEL: 'Rapla Timetable Link',
  DESIGN_THEME: 'Design Theme',
  DESIGN_THEME_DESCRIPTION: 'Of course we have a dark theme! Select your favourite appearance of Rablabla.',
  DESIGN_THEME_DARK: 'Dark',
  DESIGN_THEME_LIGHT: 'Light',
  DESIGN_THEME_ALTERNATIVE: 'Alternative',
  WEEK_STARTING_DAY: 'Week Starting Day',
  WEEK_STARTING_DAY_DESCRIPTION: 'Check if your week starts on monday!',
  LANGUAGE: 'Language',
  LANGUAGE_DESCRIPTION: 'We speek German and English.',
  CLOSE: 'Close',
};
