export default {
  APP_NAME: 'Rablabla',
  REFRESH: 'Aktualisieren',
  GITHUB: 'GitHub',
  PREFERENCES: 'Einstellungen',
  TIMETABLE_CONNECTION: 'Verbindung zum Stundenplan',
  TIMETABLE_CONNECTION_DESCRIPTION1: 'Um auf deinen Stundenplan zuzugreifen, brauchen wir den rapla Link deiner Universität bzw. deines Kurses. Dieser wird üblicherweise am Anfang des Semsters aus dem Sekretariat verschickt. An der DHBW sehen Links beispielsweise so ähnlich aus:',
  TIMETABLE_CONNECTION_SAMPLE1: 'https://rapla.dhbw-stuttgart.de/rapla?key=12345abcdef',
  TIMETABLE_CONNECTION_DESCRIPTION_OR: 'oder',
  TIMETABLE_CONNECTION_SAMPLE2: 'https://rapla.dhbw-karlsruhe.de/rapla?page=calendar&user=x&file=inf4',
  TIMETABLE_CONNECTION_LABEL: 'Rapla Timetable Link',
  TIMETABLE_CONNECTION_LABEL_VALID: '',
  TIMETABLE_CONNECTION_LABEL_INVALID: 'Ups, das sieht nicht nach einem gültigen Link aus...',
  DESIGN_THEME: 'Design',
  DESIGN_THEME_DESCRIPTION: 'Natürlich haben wir ein dunkles Design! Wähle dein Lieblingsthema von Rablabla.',
  DESIGN_THEME_DARK: 'Dunkel',
  DESIGN_THEME_LIGHT: 'Hell',
  DESIGN_THEME_ALTERNATIVE: 'Alternativ',
  WEEK_STARTING_DAY: 'Erster Tag der Woche',
  WEEK_STARTING_DAY_DESCRIPTION: 'Mach dein Häkchen, wenn bei dir die Woche am Montag beginnt!',
  LANGUAGE: 'Sprache',
  LANGUAGE_DESCRIPTION: 'Wir sprechen Deutsch und Englisch.',
  CLOSE: 'Schließen',
  ONBOARDING: 'Willkommen',
  ONBOARDING_DESCRIPTION: 'Wir freuen uns, dass du dich für Rablabla interessierst. Ein freies, open-source Projekt, gestartet von Studenten der DHBW Stuttgart.',
  LEGAL_TITLE: 'Rechtliches',
  LEGAL_DESCRIPTION1: 'Rablabla ist ein nicht-kommerzielles, rein privates Studienprojekt. Für unseren Service benutzen wir Google Fonts. ',
  LEGAL_GFONTS_MORE: 'Mehr Informationen',
  LEGAL_GFONTS_LINK: 'https://developers.google.com/fonts/faq',
  LEGAL_DESCRIPTION2: 'Rablabla selbst verwendet in seiner Originalversion keine Funktionalitäten die personenbezogene Daten persistent auf unseren Servern speichern können. Wir schützen somit deine Daten GDPR(DSGVO) konform. Durch Benutzen dieser Web Applikation akzeptierst du diese Konditionen.',
  ACCEPT: 'Zustimmen',
  DATE_PICKER_TODAY: 'Heute',
  DATE_PICKER_OK: 'OK',
  DATE_PICKER_CANCEL: 'Abbrechen',
  LESSON_DETAILS: 'Vorlesungsdetails',
  TITLE: 'Titel',
  START_DATE: 'Beginn',
  END_DATE: 'Ende',
  RESSOURCES: 'Sonstiges',
};
