export default {
  APP_NAME: 'Rablabla',
  REFRESH: 'Refresh',
  GITHUB: 'GitHub',
  PREFERENCES: 'Preferences',
  TIMETABLE_CONNECTION: 'Timetable Connection',
  TIMETABLE_CONNECTION_DESCRIPTION1: 'To access your timetable events we need the rapla link from your university. You should have received it at the start of the semester. At the DHBW it looks like for example',
  TIMETABLE_CONNECTION_SAMPLE1: 'https://rapla.dhbw-stuttgart.de/rapla?key=12345abcdef',
  TIMETABLE_CONNECTION_DESCRIPTION_OR: 'or',
  TIMETABLE_CONNECTION_SAMPLE2: 'https://rapla.dhbw-karlsruhe.de/rapla?page=calendar&user=x&file=inf4',
  TIMETABLE_CONNECTION_LABEL: 'Rapla Timetable Link',
  TIMETABLE_CONNECTION_LABEL_VALID: '',
  TIMETABLE_CONNECTION_LABEL_INVALID: 'Ups, this does not look like a valid link...',
  DESIGN_THEME: 'Design Theme',
  DESIGN_THEME_DESCRIPTION: 'Of course we have a dark theme! Select your favourite appearance of Rablabla.',
  DESIGN_THEME_DARK: 'Dark',
  DESIGN_THEME_LIGHT: 'Light',
  DESIGN_THEME_ALTERNATIVE: 'Alternative',
  WEEK_STARTING_DAY: 'Week Starting Day',
  WEEK_STARTING_DAY_DESCRIPTION: 'Check if your week starts on monday!',
  LANGUAGE: 'Language',
  LANGUAGE_DESCRIPTION: 'We speek German and English.',
  CLOSE: 'Close',
  ONBOARDING: 'Welcome',
  ONBOARDING_DESCRIPTION: 'We love to see you here on Rablabla. A free, open-source project crafted by students of the DHBW Stuttgart.',
  LEGAL_TITLE: 'Legal',
  LEGAL_DESCRIPTION1: 'Rablabla is a non-commercial, completely private educational project during the university lectures. We use Google Fonts for our services. ',
  LEGAL_GFONTS_MORE: 'More',
  LEGAL_GFONTS_LINK: 'https://developers.google.com/fonts/faq',
  LEGAL_DESCRIPTION2: 'Rablabla itself in its unmodified version does not use any functionalities which are able to store personal data persistantly on our servers. Therefore we protect your data GDPR compliant. You accept these conditions via using start using this web application.',
  ACCEPT: 'Accept',
  DATE_PICKER_TODAY: 'Today',
  DATE_PICKER_OK: 'OK',
  DATE_PICKER_CANCEL: 'Cancel',
  LESSON_DETAILS: 'Event Details',
  TITLE: 'Title',
  START_DATE: 'Begin',
  END_DATE: 'End',
  RESSOURCES: 'Ressources',
};
