export default {
  APP_NAME: 'Rablabla',
  REFRESH: 'Aktualisieren',
  GITHUB: 'GitHub',
  PREFERENCES: 'Einstellungen',
  TIMETABLE_CONNECTION: 'Verbindung zum Stundenplan',
  TIMETABLE_CONNECTION_DESCRIPTION1: 'Um auf deinen Stundenplan zuzugreifen, brauchen wir den rapla Link deiner Universität bzw. deines Kurses. Dieser wird üblicherweise am Anfang des Semsters aus dem Sekretariat verschickt. An der DHBW sehen Links beispielsweise so ähnlich aus:',
  TIMETABLE_CONNECTION_SAMPLE1: 'https://rapla.dhbw-stuttgart.de/rapla?key=12345abcdef',
  TIMETABLE_CONNECTION_DESCRIPTION_OR: 'oder',
  TIMETABLE_CONNECTION_SAMPLE2: 'https://rapla.dhbw-karlsruhe.de/rapla?page=calendar&user=x&file=inf4',
  TIMETABLE_CONNECTION_LABEL: 'Rapla Stundenplan Link',
  DESIGN_THEME: 'Design',
  DESIGN_THEME_DESCRIPTION: 'Natürlich haben wir ein dunkles Design! Wähle dein Lieblingsthema von Rablabla.',
  DESIGN_THEME_DARK: 'Dunkel',
  DESIGN_THEME_LIGHT: 'Hell',
  DESIGN_THEME_ALTERNATIVE: 'Alternativ',
  WEEK_STARTING_DAY: 'Erster Tag der Woche',
  WEEK_STARTING_DAY_DESCRIPTION: 'Mach dein Häkchen, wenn bei dir die Woche am Montag beginnt!',
  LANGUAGE: 'Sprache',
  LANGUAGE_DESCRIPTION: 'Wir sprechen Deutsch und English',
  CLOSE: 'Schließen',
};
